trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

steps:
  - task: Docker@2
    displayName: Login to Docker
    inputs:
      command: login
      containerRegistry: <DOCKER_REGISTRY>

  - task: Docker@2
    displayName: Build and push
    inputs:
      command: buildAndPush
      repository: <MAIN_PROJECT_BASE>
      tags: |
        latest

  - task: Docker@2
    displayName: Logoff from Docker
    inputs:
      command: logout
      containerRegistry: <DOCKER_REGISTRY>
