trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

steps:
  - task: Docker@2
    displayName: Login to Docker
    inputs:
      command: login
      containerRegistry: dockerHub

  - task: Docker@2
    displayName: Build and push
    inputs:
      command: buildAndPush
      repository: kaiiz3n/books-app
      tags: |
        latest
        $(Build.BuildNumber)

  - task: Docker@2
    displayName: Logoff from Docker
    inputs:
      command: logout
      containerRegistry: dockerHub
